"""initial schema

Revision ID: 1c4f4903a9f2
Revises: 
Create Date: 2026-10-05 12:31:55.801059
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1c4f4903a9f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('actor_role', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('before_snapshot', sa.JSON(), nullable=True),
    sa.Column('after_snapshot', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('correlation_id', sa.String(length=80), nullable=False),
    sa.Column('request_id', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_table('emergency_contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=180), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('authority_source', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feature_flags',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('idempotency_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope_key', sa.String(length=160), nullable=False),
    sa.Column('operation', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('request_hash', sa.String(length=128), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('result_ref', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_key', 'operation', 'idempotency_key', name='uq_idem_scope_op_key')
    )
    op.create_table('message_dispatches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('appointment_id', sa.String(length=36), nullable=True),
    sa.Column('recipient_user_id', sa.String(length=36), nullable=True),
    sa.Column('template_key', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('dispatch_key', sa.String(length=180), nullable=False),
    sa.Column('provider_message_id', sa.String(length=180), nullable=True),
    sa.Column('last_error_code', sa.String(length=120), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dispatch_key')
    )
    op.create_index(op.f('ix_message_dispatches_appointment_id'), 'message_dispatches', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_message_dispatches_tenant_id'), 'message_dispatches', ['tenant_id'], unique=False)
    op.create_table('message_webhook_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider_event_id', sa.String(length=180), nullable=False),
    sa.Column('dispatch_id', sa.String(length=36), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_signature', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_event_id')
    )
    op.create_table('pharmacies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=180), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacies_city'), 'pharmacies', ['city'], unique=False)
    op.create_table('platform_config',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('sensitive', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('public_pharmacy_duty_listings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('pharmacy_id', sa.String(length=36), nullable=False),
    sa.Column('pharmacy_display_name', sa.String(length=180), nullable=False),
    sa.Column('branch_display_name', sa.String(length=180), nullable=False),
    sa.Column('address_summary', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('duty_date', sa.String(length=10), nullable=False),
    sa.Column('duty_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duty_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_schedule_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_schedule_id')
    )
    op.create_index(op.f('ix_public_pharmacy_duty_listings_city'), 'public_pharmacy_duty_listings', ['city'], unique=False)
    op.create_index(op.f('ix_public_pharmacy_duty_listings_duty_date'), 'public_pharmacy_duty_listings', ['duty_date'], unique=False)
    op.create_index(op.f('ix_public_pharmacy_duty_listings_pharmacy_id'), 'public_pharmacy_duty_listings', ['pharmacy_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('auth_subject', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=160), nullable=True),
    sa.Column('phone_e164', sa.String(length=32), nullable=True),
    sa.Column('preferred_language', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('platform_role', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_auth_subject'), 'users', ['auth_subject'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('title_key', sa.String(length=120), nullable=False),
    sa.Column('body_key', sa.String(length=180), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('pharmacy_branches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pharmacy_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=180), nullable=False),
    sa.Column('address_summary', sa.String(length=255), nullable=True),
    sa.Column('phone_public', sa.String(length=32), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_branches_pharmacy_id'), 'pharmacy_branches', ['pharmacy_id'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('specialty', sa.String(length=120), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_providers_user_id'), 'providers', ['user_id'], unique=False)
    op.create_table('clinics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('area', sa.String(length=120), nullable=True),
    sa.Column('address_summary', sa.String(length=255), nullable=True),
    sa.Column('phone_public', sa.String(length=32), nullable=True),
    sa.Column('booking_policy', sa.String(length=32), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinics_city'), 'clinics', ['city'], unique=False)
    op.create_index(op.f('ix_clinics_provider_id'), 'clinics', ['provider_id'], unique=False)
    op.create_table('pharmacy_duty_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pharmacy_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('duty_date', sa.String(length=10), nullable=False),
    sa.Column('duty_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duty_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('verification_status', sa.String(length=24), nullable=False),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['pharmacy_branches.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_duty_city_date_status', 'pharmacy_duty_schedules', ['city', 'duty_date', 'status'], unique=False)
    op.create_index(op.f('ix_pharmacy_duty_schedules_branch_id'), 'pharmacy_duty_schedules', ['branch_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_duty_schedules_city'), 'pharmacy_duty_schedules', ['city'], unique=False)
    op.create_index(op.f('ix_pharmacy_duty_schedules_duty_date'), 'pharmacy_duty_schedules', ['duty_date'], unique=False)
    op.create_index(op.f('ix_pharmacy_duty_schedules_pharmacy_id'), 'pharmacy_duty_schedules', ['pharmacy_id'], unique=False)
    op.create_table('appointment_slots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clinic_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'start_at', name='uq_slot_provider_start')
    )
    op.create_index(op.f('ix_appointment_slots_clinic_id'), 'appointment_slots', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_appointment_slots_provider_id'), 'appointment_slots', ['provider_id'], unique=False)
    op.create_index(op.f('ix_appointment_slots_start_at'), 'appointment_slots', ['start_at'], unique=False)
    op.create_table('clinic_memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('clinic_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'clinic_id', name='uq_membership_user_clinic')
    )
    op.create_index(op.f('ix_clinic_memberships_clinic_id'), 'clinic_memberships', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_clinic_memberships_user_id'), 'clinic_memberships', ['user_id'], unique=False)
    op.create_table('provider_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clinic_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_minute', sa.Integer(), nullable=False),
    sa.Column('end_minute', sa.Integer(), nullable=False),
    sa.Column('appointment_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('breaks', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_schedules_clinic_id'), 'provider_schedules', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_provider_schedules_provider_id'), 'provider_schedules', ['provider_id'], unique=False)
    op.create_index('ix_schedule_provider_weekday', 'provider_schedules', ['provider_id', 'weekday'], unique=False)
    op.create_table('schedule_exceptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('clinic_id', sa.String(length=36), nullable=False),
    sa.Column('exception_date', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_exceptions_clinic_id'), 'schedule_exceptions', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_schedule_exceptions_exception_date'), 'schedule_exceptions', ['exception_date'], unique=False)
    op.create_index(op.f('ix_schedule_exceptions_provider_id'), 'schedule_exceptions', ['provider_id'], unique=False)
    op.create_table('appointment_holds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slot_id', sa.String(length=36), nullable=False),
    sa.Column('patient_user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['appointment_slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_holds_expires_at'), 'appointment_holds', ['expires_at'], unique=False)
    op.create_index(op.f('ix_appointment_holds_patient_user_id'), 'appointment_holds', ['patient_user_id'], unique=False)
    op.create_index(op.f('ix_appointment_holds_slot_id'), 'appointment_holds', ['slot_id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clinic_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('patient_user_id', sa.String(length=36), nullable=False),
    sa.Column('slot_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('request_status', sa.String(length=24), nullable=False),
    sa.Column('appointment_policy_version', sa.Integer(), nullable=False),
    sa.Column('scheduled_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.String(length=255), nullable=True),
    sa.Column('reschedule_of_appointment_id', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['appointment_slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_clinic_id'), 'appointments', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_user_id'), 'appointments', ['patient_user_id'], unique=False)
    op.create_index(op.f('ix_appointments_provider_id'), 'appointments', ['provider_id'], unique=False)
    op.create_index(op.f('ix_appointments_slot_id'), 'appointments', ['slot_id'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_index('uq_active_appointment_slot', 'appointments', ['slot_id'], unique=True, postgresql_where=sa.text("status NOT IN ('cancelledByPatient','cancelledByProvider','rescheduled','noShow','expired')"), sqlite_where=sa.text("status NOT IN ('cancelledByPatient','cancelledByProvider','rescheduled','noShow','expired')"))
    op.create_table('appointment_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('appointment_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('actor_role', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('from_state', sa.String(length=40), nullable=True),
    sa.Column('to_state', sa.String(length=40), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('correlation_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_events_actor_id'), 'appointment_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_appointment_events_appointment_id'), 'appointment_events', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_appointment_events_correlation_id'), 'appointment_events', ['correlation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointment_events_correlation_id'), table_name='appointment_events')
    op.drop_index(op.f('ix_appointment_events_appointment_id'), table_name='appointment_events')
    op.drop_index(op.f('ix_appointment_events_actor_id'), table_name='appointment_events')
    op.drop_table('appointment_events')
    op.drop_index('uq_active_appointment_slot', table_name='appointments', postgresql_where=sa.text("status NOT IN ('cancelledByPatient','cancelledByProvider','rescheduled','noShow','expired')"), sqlite_where=sa.text("status NOT IN ('cancelledByPatient','cancelledByProvider','rescheduled','noShow','expired')"))
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_slot_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_provider_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_user_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_clinic_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_appointment_holds_slot_id'), table_name='appointment_holds')
    op.drop_index(op.f('ix_appointment_holds_patient_user_id'), table_name='appointment_holds')
    op.drop_index(op.f('ix_appointment_holds_expires_at'), table_name='appointment_holds')
    op.drop_table('appointment_holds')
    op.drop_index(op.f('ix_schedule_exceptions_provider_id'), table_name='schedule_exceptions')
    op.drop_index(op.f('ix_schedule_exceptions_exception_date'), table_name='schedule_exceptions')
    op.drop_index(op.f('ix_schedule_exceptions_clinic_id'), table_name='schedule_exceptions')
    op.drop_table('schedule_exceptions')
    op.drop_index('ix_schedule_provider_weekday', table_name='provider_schedules')
    op.drop_index(op.f('ix_provider_schedules_provider_id'), table_name='provider_schedules')
    op.drop_index(op.f('ix_provider_schedules_clinic_id'), table_name='provider_schedules')
    op.drop_table('provider_schedules')
    op.drop_index(op.f('ix_clinic_memberships_user_id'), table_name='clinic_memberships')
    op.drop_index(op.f('ix_clinic_memberships_clinic_id'), table_name='clinic_memberships')
    op.drop_table('clinic_memberships')
    op.drop_index(op.f('ix_appointment_slots_start_at'), table_name='appointment_slots')
    op.drop_index(op.f('ix_appointment_slots_provider_id'), table_name='appointment_slots')
    op.drop_index(op.f('ix_appointment_slots_clinic_id'), table_name='appointment_slots')
    op.drop_table('appointment_slots')
    op.drop_index(op.f('ix_pharmacy_duty_schedules_pharmacy_id'), table_name='pharmacy_duty_schedules')
    op.drop_index(op.f('ix_pharmacy_duty_schedules_duty_date'), table_name='pharmacy_duty_schedules')
    op.drop_index(op.f('ix_pharmacy_duty_schedules_city'), table_name='pharmacy_duty_schedules')
    op.drop_index(op.f('ix_pharmacy_duty_schedules_branch_id'), table_name='pharmacy_duty_schedules')
    op.drop_index('ix_duty_city_date_status', table_name='pharmacy_duty_schedules')
    op.drop_table('pharmacy_duty_schedules')
    op.drop_index(op.f('ix_clinics_provider_id'), table_name='clinics')
    op.drop_index(op.f('ix_clinics_city'), table_name='clinics')
    op.drop_table('clinics')
    op.drop_index(op.f('ix_providers_user_id'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_pharmacy_branches_pharmacy_id'), table_name='pharmacy_branches')
    op.drop_table('pharmacy_branches')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_users_auth_subject'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_public_pharmacy_duty_listings_pharmacy_id'), table_name='public_pharmacy_duty_listings')
    op.drop_index(op.f('ix_public_pharmacy_duty_listings_duty_date'), table_name='public_pharmacy_duty_listings')
    op.drop_index(op.f('ix_public_pharmacy_duty_listings_city'), table_name='public_pharmacy_duty_listings')
    op.drop_table('public_pharmacy_duty_listings')
    op.drop_table('platform_config')
    op.drop_index(op.f('ix_pharmacies_city'), table_name='pharmacies')
    op.drop_table('pharmacies')
    op.drop_table('message_webhook_events')
    op.drop_index(op.f('ix_message_dispatches_tenant_id'), table_name='message_dispatches')
    op.drop_index(op.f('ix_message_dispatches_appointment_id'), table_name='message_dispatches')
    op.drop_table('message_dispatches')
    op.drop_table('idempotency_records')
    op.drop_table('feature_flags')
    op.drop_table('emergency_contacts')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
